import { Coupon, SeasonalEvent, Notification } from './types'

export const MOCK_USER_LOCATION = {
  lat: -23.55052,
  lng: -46.633308,
}

export const MOODS: { id: string; label: string; icon: string }[] = [
  { id: 'Romantic', label: 'Romântico', icon: 'Heart' },
  { id: 'Economic', label: 'Econômico', icon: 'PiggyBank' },
  { id: 'Quick Bite', label: 'Rápido', icon: 'Zap' },
  { id: 'Adventure', label: 'Aventura', icon: 'Compass' },
  { id: 'Relaxing', label: 'Relax', icon: 'Coffee' },
  { id: 'Family', label: 'Família', icon: 'Users' },
]

export const CATEGORIES: { id: string; label: string; icon: string }[] = [
  { id: 'all', label: 'Todos', icon: 'LayoutGrid' },
  { id: 'Alimentação', label: 'Alimentação', icon: 'Utensils' },
  { id: 'Moda', label: 'Moda', icon: 'Shirt' },
  { id: 'Serviços', label: 'Serviços', icon: 'Briefcase' },
  { id: 'Eletrônicos', label: 'Eletrônicos', icon: 'Smartphone' },
  { id: 'Lazer', label: 'Lazer', icon: 'Ticket' },
]

export const SEASONAL_EVENTS: SeasonalEvent[] = [
  {
    id: '1',
    title: 'Black Friday',
    date: new Date('2024-11-29'),
    description: 'As maiores ofertas do ano em todas as lojas.',
    type: 'sale',
  },
  {
    id: '2',
    title: 'Natal',
    date: new Date('2024-12-25'),
    description: 'Ofertas especiais de presentes e decoração.',
    type: 'holiday',
  },
  {
    id: '3',
    title: 'Dia do Consumidor',
    date: new Date('2024-03-15'),
    description: 'Descontos exclusivos para celebrar o consumidor.',
    type: 'sale',
  },
  {
    id: '4',
    title: 'Festival de Inverno',
    date: new Date('2024-06-21'),
    description: 'Ofertas de roupas e comidas típicas da estação.',
    type: 'event',
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Bem-vindo ao CupomGeo!',
    message: 'Explore as melhores ofertas ao seu redor.',
    type: 'system',
    read: false,
    date: new Date().toISOString(),
  },
]

export const MOCK_COUPONS: Coupon[] = [
  {
    id: '1',
    storeName: 'Burger King',
    title: '2 Whoppers por R$ 25,90',
    description:
      'Aproveite a oferta clássica de 2 sanduíches Whopper por um preço especial.',
    discount: '40% OFF',
    category: 'Alimentação',
    distance: 300,
    expiryDate: '2024-12-31',
    image: 'https://img.usecurling.com/p/600/400?q=burger%20whopper',
    logo: 'https://img.usecurling.com/i?q=burger%20king&shape=fill&color=orange',
    code: 'BK-WHOP-2X',
    isFeatured: true,
    isTrending: true,
    terms: 'Válido apenas para unidades participantes.',
    coordinates: { lat: -23.551, lng: -46.634 },
    totalAvailable: 1000,
    reservedCount: 450,
    maxPerUser: 2,
    averageRating: 4.5,
    moods: ['Quick Bite', 'Family', 'Economic'],
    loyaltyProgram: {
      totalStamps: 5,
      currentStamps: 3,
      reward: '1 Combo Grátis',
    },
    lastVerified: new Date().toISOString(),
    upvotes: 120,
    downvotes: 2,
    status: 'active',
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Carlos Silva',
        rating: 5,
        comment: 'Muito bom e barato!',
        date: '2024-01-15',
      },
      {
        id: 'r2',
        userId: 'u2',
        userName: 'Ana Costa',
        rating: 4,
        comment: 'O lanche estava ótimo.',
        date: '2024-01-16',
      },
    ],
    menu: [
      {
        name: 'Whopper',
        description: 'Hambúrguer grelhado no fogo com queijo, picles e molho.',
        price: 24.9,
        translations: {
          en: {
            name: 'Whopper',
            description:
              'Flame-grilled beef patty with cheese, pickles and sauce.',
          },
          es: {
            name: 'Whopper',
            description:
              'Hamburguesa a la parrilla con queso, pepinillos y salsa.',
          },
        },
      },
    ],
  },
  {
    id: '2',
    storeName: 'C&A Modas',
    title: 'R$ 50 de desconto em Jeans',
    description:
      'Nas compras acima de R$ 200,00 em peças jeans femininas ou masculinas.',
    discount: 'R$ 50 OFF',
    category: 'Moda',
    distance: 850,
    expiryDate: '2024-11-15',
    image: 'https://img.usecurling.com/p/600/400?q=jeans%20fashion',
    logo: 'https://img.usecurling.com/i?q=clothes&shape=fill&color=blue',
    code: 'JEANS50',
    isFeatured: true,
    terms: 'Exceto peças remarcadas.',
    coordinates: { lat: -23.548, lng: -46.636 },
    totalAvailable: 500,
    reservedCount: 120,
    maxPerUser: 1,
    averageRating: 4.0,
    moods: ['Economic'],
    reviews: [],
  },
  {
    id: '3',
    storeName: 'Cinemark',
    title: 'Ingresso 2x1 (Seg-Qui)',
    description: 'Compre um ingresso inteira e ganhe outro grátis.',
    discount: '2x1',
    category: 'Lazer',
    distance: 1200,
    expiryDate: '2024-10-30',
    image: 'https://img.usecurling.com/p/600/400?q=cinema%20popcorn',
    logo: 'https://img.usecurling.com/i?q=film&shape=fill&color=red',
    code: 'CINE2X1',
    isTrending: true,
    terms: 'Válido para sessões 2D. Não válido para feriados.',
    coordinates: { lat: -23.555, lng: -46.64 },
    totalAvailable: 200,
    reservedCount: 180,
    maxPerUser: 2,
    averageRating: 4.8,
    moods: ['Romantic', 'Relaxing', 'Family'],
    loyaltyProgram: {
      totalStamps: 10,
      currentStamps: 9,
      reward: '1 Ingresso VIP',
    },
    reviews: [
      {
        id: 'r3',
        userId: 'u3',
        userName: 'Marcos Paulo',
        rating: 5,
        comment: 'Excelente promoção.',
        date: '2024-02-10',
      },
    ],
  },
  {
    id: '4',
    storeName: 'Smart Fit',
    title: '1º Mês Grátis + Adesão Zero',
    description: 'Comece a treinar hoje mesmo sem pagar nada no primeiro mês.',
    discount: 'Grátis',
    category: 'Serviços',
    distance: 450,
    expiryDate: '2024-09-20',
    image: 'https://img.usecurling.com/p/600/400?q=gym%20workout',
    logo: 'https://img.usecurling.com/i?q=dumbbell&shape=fill&color=black',
    code: 'SMART-ZERO',
    terms: 'Válido para plano Black.',
    coordinates: { lat: -23.552, lng: -46.631 },
    averageRating: 3.5,
    moods: ['Adventure'],
    reviews: [],
  },
  {
    id: '5',
    storeName: 'Samsung Store',
    title: '15% OFF em Acessórios',
    description: 'Desconto em capas, carregadores e fones Galaxy Buds.',
    discount: '15% OFF',
    category: 'Eletrônicos',
    distance: 2500,
    expiryDate: '2024-12-01',
    image: 'https://img.usecurling.com/p/600/400?q=headphones%20tech',
    logo: 'https://img.usecurling.com/i?q=samsung&shape=fill&color=blue',
    code: 'SAMS15',
    coordinates: { lat: -23.56, lng: -46.65 },
    averageRating: 4.2,
    reviews: [],
  },
  {
    id: '6',
    storeName: "McDonald's",
    title: 'McOferta Big Mac por R$ 19,90',
    description: 'Sanduíche + Batata Média + Bebida.',
    discount: '30% OFF',
    category: 'Alimentação',
    distance: 150,
    expiryDate: '2024-11-25',
    image: 'https://img.usecurling.com/p/600/400?q=burger%20fries',
    logo: 'https://img.usecurling.com/i?q=mcdonalds&shape=fill&color=yellow',
    code: 'BIGMAC19',
    isTrending: true,
    coordinates: { lat: -23.549, lng: -46.632 },
    isSpecial: true,
    averageRating: 4.6,
    moods: ['Quick Bite', 'Family'],
    reviews: [],
  },
  {
    id: '7',
    storeName: 'Restaurante da Vila',
    title: 'Menu Executivo - Prato do Dia',
    description: 'Almoço completo com entrada, prato principal e sobremesa.',
    discount: 'R$ 35,00',
    category: 'Alimentação',
    distance: 50,
    expiryDate: '2024-12-31',
    image: 'https://img.usecurling.com/p/600/400?q=lunch%20plate',
    logo: 'https://img.usecurling.com/i?q=fork&shape=fill&color=green',
    code: 'ALMOCO35',
    isSpecial: true,
    coordinates: { lat: -23.55, lng: -46.633 },
    averageRating: 5.0,
    moods: ['Relaxing', 'Economic'],
    loyaltyProgram: {
      totalStamps: 10,
      currentStamps: 2,
      reward: '1 Almoço Grátis',
    },
    reviews: [
      {
        id: 'r4',
        userId: 'u4',
        userName: 'Julia Mendes',
        rating: 5,
        comment: 'Comida caseira deliciosa!',
        date: '2024-03-01',
      },
    ],
    menu: [
      {
        name: 'Feijoada Completa',
        description: 'Feijão preto, carnes nobres, arroz, couve e farofa.',
        price: 35.0,
        translations: {
          en: {
            name: 'Complete Feijoada',
            description:
              'Black beans stew with pork, rice, collard greens and cassava flour.',
          },
          es: {
            name: 'Feijoada Completa',
            description:
              'Estofado de frijoles negros con cerdo, arroz, col y harina de yuca.',
          },
        },
      },
    ],
  },
]
