import {
  Coupon,
  SeasonalEvent,
  Notification,
  Challenge,
  Badge,
  ABTest,
  Itinerary,
  Company,
  Advertisement,
  User,
  RewardItem,
} from './types'

export const MOCK_USER_LOCATION = {
  lat: -23.55052,
  lng: -46.633308,
}

export const MOODS: { id: string; label: string; icon: string }[] = [
  { id: 'Romantic', label: 'Romântico', icon: 'Heart' },
  { id: 'Economic', label: 'Econômico', icon: 'PiggyBank' },
  { id: 'Quick Bite', label: 'Rápido', icon: 'Zap' },
  { id: 'Adventure', label: 'Aventura', icon: 'Compass' },
  { id: 'Relaxing', label: 'Relax', icon: 'Coffee' },
  { id: 'Family', label: 'Família', icon: 'Users' },
]

export const CATEGORIES: { id: string; label: string; icon: string }[] = [
  { id: 'all', label: 'Todos', icon: 'LayoutGrid' },
  { id: 'Alimentação', label: 'Alimentação', icon: 'Utensils' },
  { id: 'Moda', label: 'Moda', icon: 'Shirt' },
  { id: 'Serviços', label: 'Serviços', icon: 'Briefcase' },
  { id: 'Eletrônicos', label: 'Eletrônicos', icon: 'Smartphone' },
  { id: 'Lazer', label: 'Lazer', icon: 'Ticket' },
  { id: 'Mercado', label: 'Mercado', icon: 'ShoppingBasket' },
  { id: 'Beleza', label: 'Beleza', icon: 'Sparkles' },
]

export const SEASONAL_EVENTS: SeasonalEvent[] = [
  {
    id: '1',
    title: 'Black Friday',
    date: new Date('2024-11-29'),
    description: 'As maiores ofertas do ano em todas as lojas.',
    type: 'sale',
    coordinates: { lat: -23.55052, lng: -46.633308 },
    image: 'https://img.usecurling.com/p/600/400?q=black%20friday',
  },
  {
    id: '2',
    title: 'Natal na Paulista',
    date: new Date('2024-12-25'),
    description:
      'Ofertas especiais de presentes e decoração com show de luzes.',
    type: 'holiday',
    coordinates: { lat: -23.5614, lng: -46.656 },
    image: 'https://img.usecurling.com/p/600/400?q=christmas%20lights',
  },
  {
    id: '3',
    title: 'Dia do Consumidor',
    date: new Date('2024-03-15'),
    description: 'Descontos exclusivos para celebrar o consumidor.',
    type: 'sale',
    coordinates: { lat: -23.5489, lng: -46.6388 },
    image: 'https://img.usecurling.com/p/600/400?q=shopping%20bag',
  },
  {
    id: '4',
    title: 'Festival Gastronômico',
    date: new Date(), // Today for demo
    description: 'Experimente pratos de chefs renomados com desconto.',
    type: 'event',
    coordinates: { lat: -23.555, lng: -46.64 },
    image: 'https://img.usecurling.com/p/600/400?q=food%20festival',
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Bem-vindo ao CupomGeo!',
    message: 'Explore as melhores ofertas ao seu redor.',
    type: 'system',
    read: false,
    date: new Date().toISOString(),
    priority: 'low',
    category: 'system',
  },
  {
    id: '2',
    title: 'Oferta Relâmpago!',
    message: '50% OFF no Burger King - Expira em 1 hora',
    type: 'deal',
    read: false,
    date: new Date(Date.now() - 3600000).toISOString(),
    priority: 'high',
    category: 'smart',
    link: '/coupon/1',
  },
]

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: '1',
    title: 'Caçador Urbano',
    description: 'Visite 5 locais diferentes este mês',
    total: 5,
    current: 3,
    reward: '500 pts',
    icon: 'MapPin',
    completed: false,
    status: 'active',
    type: 'travel',
  },
  {
    id: '2',
    title: 'Foodie Master',
    description: 'Faça 3 reservas em restaurantes',
    total: 3,
    current: 1,
    reward: 'Super Cupom',
    icon: 'Utensils',
    completed: false,
    status: 'active',
    type: 'collection',
  },
  {
    id: '3',
    title: 'Explorador',
    description: 'Envie 2 novos cupons',
    total: 2,
    current: 2,
    reward: 'Badge',
    icon: 'Camera',
    completed: true,
    status: 'completed',
    type: 'social',
  },
  {
    id: '4',
    title: 'Rota Histórica',
    description: 'Complete a rota "Centro Histórico"',
    total: 1,
    current: 0,
    reward: 'Badge Historiador',
    icon: 'Landmark',
    completed: false,
    status: 'available',
    type: 'travel',
  },
]

export const MOCK_BADGES: Badge[] = [
  {
    id: '1',
    name: 'Iniciante',
    description: 'Primeiro acesso',
    image: 'https://img.usecurling.com/i?q=medal&color=yellow',
    earnedDate: '2024-01-10',
  },
  {
    id: '2',
    name: 'Explorador',
    description: 'Contribuiu com ofertas',
    image: 'https://img.usecurling.com/i?q=compass&color=blue',
    earnedDate: '2024-02-15',
  },
]

export const MOCK_COUPONS: Coupon[] = [
  {
    id: '1',
    storeName: 'Burger King',
    title: '2 Whoppers por R$ 25,90',
    description:
      'Aproveite a oferta clássica de 2 sanduíches Whopper por um preço especial.',
    discount: '40% OFF',
    category: 'Alimentação',
    distance: 300,
    expiryDate: '2024-12-31',
    image: 'https://img.usecurling.com/p/600/400?q=burger%20whopper',
    logo: 'https://img.usecurling.com/i?q=burger%20king&shape=fill&color=orange',
    code: 'BK-WHOP-2X',
    isFeatured: true,
    isTrending: true,
    terms: 'Válido apenas para unidades participantes.',
    coordinates: { lat: -23.551, lng: -46.634 },
    totalAvailable: 1000,
    reservedCount: 450,
    maxPerUser: 2,
    averageRating: 4.5,
    moods: ['Quick Bite', 'Family', 'Economic'],
    loyaltyProgram: {
      totalStamps: 5,
      currentStamps: 3,
      reward: '1 Combo Grátis',
    },
    lastVerified: new Date().toISOString(),
    upvotes: 120,
    downvotes: 2,
    status: 'active',
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Carlos Silva',
        rating: 5,
        comment: 'Muito bom e barato!',
        date: '2024-01-15',
      },
    ],
    menu: [
      {
        name: 'Whopper',
        description: 'Hambúrguer grelhado no fogo.',
        price: 24.9,
        translations: {
          en: { name: 'Whopper', description: 'Flame-grilled beef patty.' },
        },
      },
    ],
    source: 'partner',
  },
  {
    id: '7',
    storeName: 'Restaurante da Vila',
    title: 'Menu Executivo - Prato do Dia',
    description: 'Almoço completo com entrada, prato principal e sobremesa.',
    discount: 'R$ 35,00',
    category: 'Alimentação',
    distance: 50,
    expiryDate: '2024-12-31',
    image: 'https://img.usecurling.com/p/600/400?q=lunch%20plate',
    logo: 'https://img.usecurling.com/i?q=fork&shape=fill&color=green',
    code: 'ALMOCO35',
    isSpecial: true,
    coordinates: { lat: -23.55, lng: -46.633 },
    averageRating: 5.0,
    moods: ['Relaxing', 'Economic'],
    acceptsBooking: true,
    reviews: [],
    menu: [],
    source: 'partner',
  },
  {
    id: '2',
    storeName: 'C&A Modas',
    title: 'R$ 50 de desconto em Jeans',
    description: 'Nas compras acima de R$ 200,00 em peças jeans.',
    discount: 'R$ 50 OFF',
    category: 'Moda',
    distance: 850,
    expiryDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://img.usecurling.com/p/600/400?q=jeans%20fashion',
    logo: 'https://img.usecurling.com/i?q=clothes&shape=fill&color=blue',
    code: 'JEANS50',
    isFeatured: true,
    coordinates: { lat: -23.548, lng: -46.636 },
    totalAvailable: 500,
    reservedCount: 120,
    averageRating: 4.0,
    reviews: [],
    source: 'aggregated',
  },
  {
    id: 'premium1',
    storeName: 'Spa Relax',
    title: 'Massagem Relaxante Completa',
    description: '60 minutos de massagem relaxante com pedras quentes.',
    discount: '30% OFF',
    category: 'Serviços',
    distance: 1200,
    expiryDate: '2024-12-20',
    image: 'https://img.usecurling.com/p/600/400?q=spa%20massage',
    logo: 'https://img.usecurling.com/i?q=lotus&shape=fill&color=violet',
    code: 'SPA-LUXO',
    isFeatured: true,
    isSpecial: true,
    coordinates: { lat: -23.555, lng: -46.64 },
    price: 89.9,
    totalAvailable: 20,
    reservedCount: 5,
    averageRating: 4.8,
    moods: ['Relaxing'],
    acceptsBooking: true,
    reviews: [],
    source: 'partner',
  },
  // New Aggregator Deals (US Context - Orlando/Kissimmee)
  {
    id: 'grp1',
    storeName: 'Groupon',
    title: 'Passeio de Helicóptero',
    description: 'Vista aérea incrível dos parques temáticos.',
    discount: '25% OFF',
    category: 'Lazer',
    distance: 5000,
    expiryDate: '2025-12-31',
    image: 'https://img.usecurling.com/p/600/400?q=helicopter%20tour',
    logo: 'https://img.usecurling.com/i?q=groupon&shape=fill&color=green',
    code: 'GRP-HELI',
    source: 'aggregated',
    coordinates: { lat: 28.35, lng: -81.55 },
  },
  {
    id: 'sim1',
    storeName: 'ShopSimon',
    title: 'Outlet Premium Voucher',
    description: 'Descontos adicionais em marcas de luxo.',
    discount: 'VIP Book',
    category: 'Moda',
    distance: 2000,
    expiryDate: '2025-06-30',
    image: 'https://img.usecurling.com/p/600/400?q=outlet%20shopping',
    logo: 'https://img.usecurling.com/i?q=bag&shape=fill&color=blue',
    code: 'SIMON-VIP',
    source: 'aggregated',
    coordinates: { lat: 28.4735, lng: -81.4533 },
  },
  {
    id: 'sep1',
    storeName: 'Sephora',
    title: 'Kit de Beleza Grátis',
    description: 'Na compra de 2 produtos da linha própria.',
    discount: 'Brinde',
    category: 'Beleza',
    distance: 3000,
    expiryDate: '2025-01-31',
    image: 'https://img.usecurling.com/p/600/400?q=makeup%20kit',
    logo: 'https://img.usecurling.com/i?q=lipstick&shape=fill&color=black',
    code: 'SEPH-GIFT',
    source: 'aggregated',
    coordinates: { lat: 28.48, lng: -81.43 },
  },
  {
    id: 'ult1',
    storeName: 'Ulta Beauty',
    title: '20% em Cuidados com Cabelo',
    description: 'Válido para todas as marcas profissionais.',
    discount: '20% OFF',
    category: 'Beleza',
    distance: 4000,
    expiryDate: '2025-02-15',
    image: 'https://img.usecurling.com/p/600/400?q=hair%20salon',
    logo: 'https://img.usecurling.com/i?q=scissors&shape=fill&color=orange',
    code: 'ULTA-20',
    source: 'aggregated',
    coordinates: { lat: 28.39, lng: -81.5 },
  },
  {
    id: 'pub1',
    storeName: 'Publix',
    title: 'Publix Subs - BOGO',
    description: 'Compre um sanduíche e ganhe outro.',
    discount: 'BOGO',
    category: 'Alimentação',
    distance: 1000,
    expiryDate: '2025-01-20',
    image: 'https://img.usecurling.com/p/600/400?q=sandwich',
    logo: 'https://img.usecurling.com/i?q=cart&shape=fill&color=green',
    code: 'PUB-SUB',
    source: 'aggregated',
    coordinates: { lat: 28.37, lng: -81.52 },
  },
  {
    id: 'wal1',
    storeName: 'Walmart',
    title: 'Desconto em Eletrônicos',
    description: 'Liquidação de TVs e acessórios.',
    discount: 'Até 40%',
    category: 'Eletrônicos',
    distance: 1500,
    expiryDate: '2025-03-01',
    image: 'https://img.usecurling.com/p/600/400?q=tv%20store',
    logo: 'https://img.usecurling.com/i?q=mart&shape=fill&color=blue',
    code: 'WAL-ELECT',
    source: 'aggregated',
    coordinates: { lat: 28.34, lng: -81.49 },
  },
  {
    id: 'orl1',
    storeName: 'Orlando Theme Park',
    title: 'Fast Pass Universal',
    description: 'Corte as filas nos melhores brinquedos da Universal.',
    discount: '20% OFF',
    category: 'Lazer',
    distance: 0,
    expiryDate: '2025-06-30',
    image: 'https://img.usecurling.com/p/600/400?q=theme%20park',
    logo: 'https://img.usecurling.com/i?q=globe&shape=fill&color=blue',
    code: 'UNIV-FAST-20',
    isFeatured: true,
    coordinates: { lat: 28.5383, lng: -81.3792 },
    totalAvailable: 500,
    reservedCount: 150,
    averageRating: 4.9,
    reviews: [],
    source: 'partner',
  },
]

export const MOCK_AB_TESTS: ABTest[] = [
  {
    id: 'ab1',
    couponId: '1',
    startDate: '2024-10-01',
    endDate: '2024-10-15',
    status: 'active',
    variantA: {
      id: 'vA',
      name: 'Imagem Padrão',
      title: '2 Whoppers por R$ 25,90',
      discount: '40% OFF',
      image: 'https://img.usecurling.com/p/600/400?q=burger%20whopper',
      views: 1200,
      clicks: 450,
      redemptions: 89,
    },
    variantB: {
      id: 'vB',
      name: 'Imagem Lifestyle',
      title: 'Oferta Imperdível: Combo Whopper',
      discount: '40% OFF',
      image: 'https://img.usecurling.com/p/600/400?q=people%20eating%20burger',
      views: 1150,
      clicks: 520,
      redemptions: 112,
    },
  },
]

export const MOCK_ITINERARIES: Itinerary[] = [
  {
    id: 'it1',
    title: 'Tour Gastronômico Econômico',
    description:
      'Um passeio pelos sabores da cidade sem gastar muito. Inclui almoço, lanche e jantar com descontos.',
    stops: [MOCK_COUPONS[0], MOCK_COUPONS[1]],
    days: [
      {
        id: 'd1',
        dayNumber: 1,
        stops: [MOCK_COUPONS[0], MOCK_COUPONS[1]],
      },
    ],
    totalSavings: 60,
    duration: '4h',
    image: 'https://img.usecurling.com/p/600/300?q=food%20tour',
    tags: ['Gastronomia', 'Econômico'],
    matchScore: 95,
  },
  {
    id: 'template1',
    title: 'Orlando 10 Dias Completo',
    description:
      'Roteiro completo para curtir os parques e compras em Orlando.',
    stops: [],
    days: Array.from({ length: 10 }).map((_, i) => ({
      id: `d${i + 1}`,
      dayNumber: i + 1,
      stops: i === 0 ? [MOCK_COUPONS[6]] : [],
    })),
    totalSavings: 450,
    duration: '10 Dias',
    image: 'https://img.usecurling.com/p/600/300?q=orlando%20park',
    tags: ['Família', 'Internacional', 'Template'],
    matchScore: 100,
    isTemplate: true,
  },
]

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Burger King',
    email: 'contact@bk.com',
    status: 'active',
    registrationDate: '2024-01-01',
    region: 'São Paulo, SP',
  },
  {
    id: 'c2',
    name: 'Restaurante da Vila',
    email: 'admin@vila.com',
    status: 'active',
    registrationDate: '2024-02-14',
    region: 'São Paulo, SP',
  },
]

export const MOCK_ADS: Advertisement[] = [
  {
    id: 'ad1',
    title: 'Verão Burger King',
    companyId: 'c1',
    region: 'São Paulo, SP',
    category: 'Alimentação',
    billingType: 'fixed',
    placement: 'top',
    status: 'active',
    views: 15000,
    clicks: 3400,
    startDate: '2024-12-01',
    endDate: '2025-01-31',
    image: 'https://img.usecurling.com/p/800/200?q=burger%20ad',
    link: 'https://burgerking.com.br',
  },
  {
    id: 'ad2',
    title: 'Seguro Viagem Promo',
    companyId: 'admin',
    region: 'Brasil',
    category: 'Serviços',
    billingType: 'ppc',
    placement: 'bottom',
    status: 'active',
    views: 8000,
    clicks: 500,
    startDate: '2024-12-01',
    endDate: '2025-12-31',
    image: 'https://img.usecurling.com/p/800/200?q=travel%20insurance',
    link: 'https://seguros.com.br',
  },
]

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Admin User',
    email: 'admin@dealvoy.com',
    role: 'admin',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male',
    birthday: '1990-05-15',
  },
  {
    id: 'u2',
    name: 'João da Silva',
    email: 'joao@email.com',
    role: 'user',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male',
    birthday: '1995-10-20',
  },
]

export const MOCK_REWARDS: RewardItem[] = [
  {
    id: 'r1',
    title: 'Voucher R$ 20 iFood',
    description: 'Vale presente para usar em qualquer pedido no iFood.',
    cost: 1500,
    image: 'https://img.usecurling.com/i?q=food&color=red&shape=fill',
    category: 'coupon',
    available: true,
  },
  {
    id: 'r2',
    title: 'Ingresso Cinema VIP',
    description: 'Par de ingressos para qualquer sessão Cinemark.',
    cost: 2500,
    image: 'https://img.usecurling.com/i?q=cinema&color=blue&shape=fill',
    category: 'experience',
    available: true,
  },
]
