export const exportToCSV = (
  headers: string[],
  rows: string[][],
  filename: string,
) => {
  const csvContent = [
    headers.join(','),
    ...rows.map((row) =>
      row
        .map((cell) => `"${String(cell || '').replace(/"/g, '""')}"`)
        .join(','),
    ),
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = filename
  link.click()
}

export const exportToPDF = (
  headers: string[],
  rows: string[][],
  filename: string,
  title: string,
) => {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { 
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; 
          padding: 30px; 
          color: #334155;
        }
        .header {
          display: flex;
          align-items: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 10px;
        }
        .title { 
          font-size: 24px; 
          font-weight: 700; 
          color: #0f172a;
          margin: 0;
        }
        table { 
          width: 100%; 
          border-collapse: collapse; 
          font-size: 13px;
        }
        th, td { 
          border: 1px solid #cbd5e1; 
          padding: 10px 12px; 
          text-align: left; 
        }
        th { 
          background-color: #f8fafc; 
          font-weight: 600;
          color: #475569;
        }
        tr:nth-child(even) {
          background-color: #f8fafc;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 11px;
          color: #94a3b8;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">${title}</h1>
      </div>
      <table>
        <thead>
          <tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${rows.map((row) => `<tr>${row.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}
        </tbody>
      </table>
      <div class="footer">
        Generated by Deal Voy Analytics • ${new Date().toLocaleDateString()}
      </div>
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          }, 500);
        };
      </script>
    </body>
    </html>
  `
  const win = window.open('', '', 'width=1000,height=800')
  if (win) {
    win.document.write(html)
    win.document.close()
  }
}
