export const exportToCSV = (
  headers: string[],
  rows: string[][],
  filename: string,
) => {
  const csvContent = [
    headers.join(','),
    ...rows.map((row) =>
      row
        .map((cell) => `"${String(cell || '').replace(/"/g, '""')}"`)
        .join(','),
    ),
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = filename
  link.click()
}

export const exportToPDF = (
  headers: string[],
  rows: string[][],
  filename: string,
  title: string,
) => {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { 
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; 
          padding: 30px; 
          color: #334155;
        }
        .header {
          display: flex;
          align-items: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 10px;
        }
        .title { 
          font-size: 24px; 
          font-weight: 700; 
          color: #0f172a;
          margin: 0;
        }
        table { 
          width: 100%; 
          border-collapse: collapse; 
          font-size: 13px;
        }
        th, td { 
          border: 1px solid #cbd5e1; 
          padding: 10px 12px; 
          text-align: left; 
        }
        th { 
          background-color: #f8fafc; 
          font-weight: 600;
          color: #475569;
        }
        tr:nth-child(even) {
          background-color: #f8fafc;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 11px;
          color: #94a3b8;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">${title}</h1>
      </div>
      <table>
        <thead>
          <tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr>
        </thead>
        <tbody>
          ${rows.map((row) => `<tr>${row.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}
        </tbody>
      </table>
      <div class="footer">
        Generated by Deal Voy Analytics • ${new Date().toLocaleDateString()}
      </div>
      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
          }, 500);
        };
      </script>
    </body>
    </html>
  `
  const win = window.open('', '', 'width=1000,height=800')
  if (win) {
    win.document.write(html)
    win.document.close()
  }
}

export const exportAccountingData = (
  franchise: any,
  merchants: any[],
  t: any,
) => {
  const country = (
    franchise.addressCountry ||
    franchise.region ||
    ''
  ).toLowerCase()
  const isBrazil =
    country.includes('brasil') || country.includes('brazil') || country === 'br'

  if (isBrazil) {
    const headers = [
      'Código',
      'Razão Social',
      'Nome Fantasia',
      'CNPJ',
      'Inscrição Estadual',
      'Email',
      'Telefone',
      'Status',
      'Data de Registro',
      'Data de Expiração',
      'Site de Origem',
      'Data de Busca',
    ]
    const rows = merchants.map((m) => [
      m.id,
      m.legalName || m.name,
      m.name,
      m.taxId || '',
      m.stateRegistration || '',
      m.email || '',
      m.businessPhone || '',
      m.status.toUpperCase(),
      m.registrationDate
        ? new Date(m.registrationDate).toLocaleDateString('pt-BR')
        : '',
      m.expiryDate ? new Date(m.expiryDate).toLocaleDateString('pt-BR') : '',
      m.externalUrl || m.sourceId || '',
      m.capturedAt ? new Date(m.capturedAt).toLocaleDateString('pt-BR') : '',
    ])
    exportToCSV(
      headers,
      rows,
      `Contabilidade_BR_${franchise.name.replace(/\s+/g, '_')}.csv`,
    )
    return t(
      'admin.franchises.export_br_success',
      'Brazilian Accounting format exported successfully',
    )
  } else {
    const headers = [
      '*Customer',
      'NAME',
      'COMPANYNAME',
      'BILLA/C',
      'EMAIL',
      'PHONE',
      'TERMS',
      'TAXABLE',
      'EXPIRATION_DATE',
      'SOURCE_SITE',
      'FETCH_DATE',
    ]
    const rows = merchants.map((m) => [
      'Customer',
      m.name,
      m.legalName || m.name,
      m.taxId || '',
      m.email || '',
      m.businessPhone || '',
      'Net 30',
      'Y',
      m.expiryDate ? new Date(m.expiryDate).toISOString().split('T')[0] : '',
      m.externalUrl || m.sourceId || '',
      m.capturedAt ? new Date(m.capturedAt).toISOString().split('T')[0] : '',
    ])
    exportToCSV(
      headers,
      rows,
      `QuickBooks_Export_${franchise.name.replace(/\s+/g, '_')}.csv`,
    )
    return t(
      'admin.franchises.export_quickbooks_success',
      'QuickBooks format exported successfully',
    )
  }
}
