import React, { createContext, useContext, useState } from 'react'

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'nav.home': 'Início',
    'nav.explore': 'Explorar',
    'nav.challenges': 'Desafios',
    'nav.saved': 'Salvos',
    'nav.upload': 'Subir Doc',
    'nav.profile': 'Perfil',
    'nav.travel': 'Roteiros',
    'nav.vendor': 'Portal B2B',
    'nav.seasonal': 'Sazonal',
    'nav.admin': 'Admin',
    'search.placeholder': 'Onde você quer economizar hoje?',
    'hero.title': 'Deal Voy: Economia em movimento',
    'hero.subtitle':
      'Descubra descontos exclusivos e planeje roteiros inteligentes na sua região.',
    'coupon.reserve': 'Pegar Cupom',
    'coupon.reserved': 'Cupom Garantido',
    'coupon.available': 'Disponíveis',
    'coupon.menu': 'Ver Menu Traduzido',
    'coupon.reviews': 'Avaliações',
    'coupon.add_review': 'Adicionar Avaliação',
    'coupon.rating': 'Sua nota',
    'coupon.comment': 'Seu comentário',
    'coupon.submit_review': 'Enviar Avaliação',
    'coupon.loyalty': 'Programa de Fidelidade',
    'coupon.collect_stamp': 'Você tem selos acumulados',
    'coupon.reward': 'Recompensa',
    'coupon.report': 'Reportar Problema',
    'coupon.verify': 'Esta oferta ainda está ativa?',
    'coupon.verified_at': 'Verificado em',
    'upload.history': 'Histórico',
    'upload.camera': 'Câmera',
    'upload.pending': 'Em Análise',
    'upload.verified': 'Verificado',
    'upload.rejected': 'Rejeitado',
    'mood.title': 'Qual sua vibe hoje?',
    'common.refresh': 'Atualizar Ofertas',
    'travel.title': 'Planejador de Viagem',
    'travel.subtitle': 'Planeje sua economia, não importa onde você esteja.',
    'travel.gps': 'GPS Atual',
    'travel.plan_destination': 'Planejar Destino',
    'travel.search_placeholder': 'Para onde você vai? (Ex: Orlando, FL)',
    'travel.showing_offers_for': 'Exibindo ofertas para:',
    'travel.events': 'Eventos Locais',
    'travel.savings': 'Economia Total',
    'travel.my_itinerary': 'Meu Roteiro',
    'travel.offers_found': 'ofertas encontradas',
    'travel.no_offers': 'Nenhuma oferta encontrada nesta região.',
    'travel.back_to_gps': 'Voltar ao GPS atual',
    'travel.itinerary_title': 'Meu Roteiro de Economia',
    'travel.saved_coupons': 'cupons salvos para sua viagem.',
    'travel.empty_itinerary': 'Seu roteiro está vazio',
    'travel.empty_desc':
      'Explore ofertas e clique em "Add Trip" para organizar sua viagem.',
    'travel.explore_offers': 'Explorar Ofertas',
    'seasonal.title': 'Calendário Sazonal',
    'notifications.title': 'Notificações',
    'notifications.empty': 'Sem novas notificações',
    'notifications.mark_read': 'Marcar como lida',
    'offline.mode': 'Modo Offline',
    'offline.message': 'Você está offline. Exibindo roteiros baixados.',
    'common.view': 'Ver',
    'common.close': 'Fechar',
    'common.search': 'Buscar',
    'common.hide': 'Ocultar',
    'common.show': 'Mostrar',
    'common.share': 'Compartilhar',
    'common.view_all': 'Ver tudo',
    'common.load_more': 'Carregar Mais',
    'map.error': 'Não foi possível carregar o mapa.',
    'map.loading': 'Carregando mapa...',
    'home.detecting_location': 'Detectando localização...',
    'home.current_location': 'Localização atual:',
    'home.featured_deals': 'Ofertas em Destaque',
    'home.travel_card_title': 'Vai viajar? Economize no caminho.',
    'home.travel_card_desc':
      'Trace sua rota e descubra paradas estratégicas com descontos exclusivos em postos, restaurantes e hotéis.',
    'home.plan_route': 'Planejar Rota Agora',
    'home.tracked_deals': 'Achados da Web (Tracked)',
    'home.all_offers': 'Todas as Ofertas',
    'home.offers_of': 'Ofertas de',
    'home.no_offers':
      'Nenhuma oferta encontrada para esta categoria no momento.',
    'explore.filters': 'Filtros',
    'explore.filter_title': 'Filtrar Ofertas',
    'explore.filter_desc': 'Encontre o que você precisa',
    'explore.max_distance': 'Distância Máxima',
    'explore.categories': 'Categorias',
    'explore.apply_filters': 'Aplicar Filtros',
    'explore.view_map': 'Ver Mapa',
    'explore.view_list': 'Ver Lista',
    'vendor.dashboard': 'Painel do Parceiro',
    'vendor.add': 'Nova Campanha',
    'challenges.title': 'Desafios & Recompensas',
    'challenges.subtitle':
      'Complete missões, ganhe badges e desbloqueie descontos exclusivos.',
    'challenges.active': 'Ativos',
    'challenges.available': 'Disponíveis',
    'challenges.completed': 'Concluídos',
    'challenges.reward': 'Recompensa',
    'challenges.progress': 'Progresso',
    'challenges.accept': 'Aceitar Desafio',
    'challenges.empty': 'Você não tem desafios ativos no momento.',
    'checkout.title': 'Checkout Seguro',
    'checkout.secure': 'Seus dados estão criptografados por Deal Voy',
    'checkout.payment_method': 'Forma de Pagamento',
    'checkout.pay': 'Pagar',
    'checkout.success': 'Pagamento Confirmado!',
    'checkout.redirect': 'Redirecionando para seu cupom...',
    'ad.sponsored': 'Patrocinado',
    'notification.deal': 'Oferta',
    'notification.alert': 'Alerta',
    'notification.event': 'Evento',
  },
  en: {
    'nav.home': 'Home',
    'nav.explore': 'Explore',
    'nav.challenges': 'Challenges',
    'nav.saved': 'Saved',
    'nav.upload': 'Upload Doc',
    'nav.profile': 'Profile',
    'nav.travel': 'Itineraries',
    'nav.vendor': 'B2B Portal',
    'nav.seasonal': 'Seasonal',
    'nav.admin': 'Admin',
    'search.placeholder': 'Where do you want to save today?',
    'hero.title': 'Deal Voy: Savings in Motion',
    'hero.subtitle':
      'Discover exclusive discounts and plan smart itineraries in your area.',
    'coupon.reserve': 'Get Coupon',
    'coupon.reserved': 'Coupon Secured',
    'coupon.available': 'Available',
    'coupon.menu': 'View Translated Menu',
    'coupon.reviews': 'Reviews',
    'coupon.add_review': 'Add Review',
    'coupon.rating': 'Your rating',
    'coupon.comment': 'Your comment',
    'coupon.submit_review': 'Submit Review',
    'coupon.loyalty': 'Loyalty Program',
    'coupon.collect_stamp': 'You have collected stamps',
    'coupon.reward': 'Reward',
    'coupon.report': 'Report Issue',
    'coupon.verify': 'Is this offer still active?',
    'coupon.verified_at': 'Verified at',
    'upload.history': 'History',
    'upload.camera': 'Camera',
    'upload.pending': 'Pending',
    'upload.verified': 'Verified',
    'upload.rejected': 'Rejected',
    'mood.title': 'What is your mood today?',
    'common.refresh': 'Refresh Deals',
    'travel.title': 'Trip Planner',
    'travel.subtitle': 'Plan your savings, no matter where you are.',
    'travel.gps': 'Current GPS',
    'travel.plan_destination': 'Plan Destination',
    'travel.search_placeholder': 'Where are you going? (e.g. Orlando, FL)',
    'travel.showing_offers_for': 'Showing offers for:',
    'travel.events': 'Local Events',
    'travel.savings': 'Total Savings',
    'travel.my_itinerary': 'My Itinerary',
    'travel.offers_found': 'offers found',
    'travel.no_offers': 'No offers found in this region.',
    'travel.back_to_gps': 'Back to Current GPS',
    'travel.itinerary_title': 'My Savings Itinerary',
    'travel.saved_coupons': 'saved coupons for your trip.',
    'travel.empty_itinerary': 'Your itinerary is empty',
    'travel.empty_desc':
      'Explore offers and click "Add Trip" to organize your journey.',
    'travel.explore_offers': 'Explore Offers',
    'seasonal.title': 'Seasonal Calendar',
    'notifications.title': 'Notifications',
    'notifications.empty': 'No new notifications',
    'notifications.mark_read': 'Mark as read',
    'offline.mode': 'Offline Mode',
    'offline.message': 'You are offline. Showing downloaded itineraries.',
    'common.view': 'View',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.hide': 'Hide',
    'common.show': 'Show',
    'common.share': 'Share',
    'common.view_all': 'View all',
    'common.load_more': 'Load More',
    'map.error': 'Could not load map.',
    'map.loading': 'Loading map...',
    'home.detecting_location': 'Detecting location...',
    'home.current_location': 'Current location:',
    'home.featured_deals': 'Featured Deals',
    'home.travel_card_title': 'Traveling? Save on the way.',
    'home.travel_card_desc':
      'Trace your route and discover strategic stops with exclusive discounts at gas stations, restaurants, and hotels.',
    'home.plan_route': 'Plan Route Now',
    'home.tracked_deals': 'Web Finds (Tracked)',
    'home.all_offers': 'All Offers',
    'home.offers_of': 'Offers of',
    'home.no_offers': 'No offers found for this category at the moment.',
    'explore.filters': 'Filters',
    'explore.filter_title': 'Filter Offers',
    'explore.filter_desc': 'Find what you need',
    'explore.max_distance': 'Max Distance',
    'explore.categories': 'Categories',
    'explore.apply_filters': 'Apply Filters',
    'explore.view_map': 'View Map',
    'explore.view_list': 'View List',
    'vendor.dashboard': 'Partner Dashboard',
    'vendor.add': 'New Campaign',
    'challenges.title': 'Challenges & Rewards',
    'challenges.subtitle':
      'Complete missions, earn badges and unlock exclusive discounts.',
    'challenges.active': 'Active',
    'challenges.available': 'Available',
    'challenges.completed': 'Completed',
    'challenges.reward': 'Reward',
    'challenges.progress': 'Progress',
    'challenges.accept': 'Accept Challenge',
    'challenges.empty': 'You have no active challenges at the moment.',
    'checkout.title': 'Secure Checkout',
    'checkout.secure': 'Your data is encrypted by Deal Voy',
    'checkout.payment_method': 'Payment Method',
    'checkout.pay': 'Pay',
    'checkout.success': 'Payment Confirmed!',
    'checkout.redirect': 'Redirecting to your coupon...',
    'ad.sponsored': 'Sponsored',
    'notification.deal': 'Deal',
    'notification.alert': 'Alert',
    'notification.event': 'Event',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.explore': 'Explorar',
    'nav.challenges': 'Desafíos',
    'nav.saved': 'Guardados',
    'nav.upload': 'Subir Doc',
    'nav.profile': 'Perfil',
    'nav.travel': 'Rutas',
    'nav.vendor': 'Portal B2B',
    'nav.seasonal': 'Estacional',
    'nav.admin': 'Admin',
    'search.placeholder': '¿Dónde quieres ahorrar hoy?',
    'hero.title': 'Deal Voy: Ahorro en Movimiento',
    'hero.subtitle':
      'Descubre descuentos exclusivos y planifica itinerarios inteligentes en tu zona.',
    'coupon.reserve': 'Obtener Cupón',
    'coupon.reserved': 'Cupón Asegurado',
    'coupon.available': 'Disponibles',
    'coupon.menu': 'Ver Menú Traducido',
    'coupon.reviews': 'Reseñas',
    'coupon.add_review': 'Agregar Reseña',
    'coupon.rating': 'Tu calificación',
    'coupon.comment': 'Tu comentario',
    'coupon.submit_review': 'Enviar Reseña',
    'coupon.loyalty': 'Programa de Lealtad',
    'coupon.collect_stamp': 'Tienes sellos acumulados',
    'coupon.reward': 'Recompensa',
    'coupon.report': 'Reportar Problema',
    'coupon.verify': '¿Sigue activa esta oferta?',
    'coupon.verified_at': 'Verificado en',
    'upload.history': 'Historial',
    'upload.camera': 'Cámara',
    'upload.pending': 'Pendiente',
    'upload.verified': 'Verificado',
    'upload.rejected': 'Rechazado',
    'mood.title': '¿Cuál es tu humor hoy?',
    'common.refresh': 'Actualizar Ofertas',
    'travel.title': 'Planificador de Viaje',
    'travel.subtitle': 'Planifica tu ahorro, sin importar dónde estés.',
    'travel.gps': 'GPS Actual',
    'travel.plan_destination': 'Planificar Destino',
    'travel.search_placeholder': '¿A dónde vas? (Ej: Orlando, FL)',
    'travel.showing_offers_for': 'Mostrando ofertas para:',
    'travel.events': 'Eventos Locales',
    'travel.savings': 'Ahorro Total',
    'travel.my_itinerary': 'Mi Itinerario',
    'travel.offers_found': 'ofertas encontradas',
    'travel.no_offers': 'No se encontraron ofertas en esta región.',
    'travel.back_to_gps': 'Volver al GPS actual',
    'travel.itinerary_title': 'Mi Itinerario de Ahorro',
    'travel.saved_coupons': 'cupones guardados para tu viaje.',
    'travel.empty_itinerary': 'Tu itinerario está vacío',
    'travel.empty_desc':
      'Explora ofertas y haz clic en "Add Trip" para organizar tu viaje.',
    'travel.explore_offers': 'Explorar Ofertas',
    'seasonal.title': 'Calendario Estacional',
    'notifications.title': 'Notificaciones',
    'notifications.empty': 'Sin nuevas notificaciones',
    'notifications.mark_read': 'Marcar como leída',
    'offline.mode': 'Modo Offline',
    'offline.message': 'Estás sin internet. Mostrando itinerarios descargados.',
    'common.view': 'Ver',
    'common.close': 'Cerrar',
    'common.search': 'Buscar',
    'common.hide': 'Ocultar',
    'common.show': 'Mostrar',
    'common.share': 'Compartir',
    'common.view_all': 'Ver todo',
    'common.load_more': 'Cargar Más',
    'map.error': 'No se pudo cargar el mapa.',
    'map.loading': 'Cargando mapa...',
    'home.detecting_location': 'Detectando ubicación...',
    'home.current_location': 'Ubicación actual:',
    'home.featured_deals': 'Ofertas Destacadas',
    'home.travel_card_title': '¿Vas a viajar? Ahorra en el camino.',
    'home.travel_card_desc':
      'Traza tu ruta y descubre paradas estratégicas con descuentos exclusivos en estaciones, restaurantes y hoteles.',
    'home.plan_route': 'Planificar Ruta Ahora',
    'home.tracked_deals': 'Hallazgos Web (Tracked)',
    'home.all_offers': 'Todas las Ofertas',
    'home.offers_of': 'Ofertas de',
    'home.no_offers':
      'No se encontraron ofertas para esta categoría en este momento.',
    'explore.filters': 'Filtros',
    'explore.filter_title': 'Filtrar Ofertas',
    'explore.filter_desc': 'Encuentra lo que necesitas',
    'explore.max_distance': 'Distancia Máxima',
    'explore.categories': 'Categorías',
    'explore.apply_filters': 'Aplicar Filtros',
    'explore.view_map': 'Ver Mapa',
    'explore.view_list': 'Ver Lista',
    'vendor.dashboard': 'Panel de Socio',
    'vendor.add': 'Nueva Campaña',
    'challenges.title': 'Desafíos y Recompensas',
    'challenges.subtitle':
      'Completa misiones, gana insignias y desbloquea descuentos exclusivos.',
    'challenges.active': 'Activos',
    'challenges.available': 'Disponibles',
    'challenges.completed': 'Completados',
    'challenges.reward': 'Recompensa',
    'challenges.progress': 'Progreso',
    'challenges.accept': 'Aceptar Desafío',
    'challenges.empty': 'No tienes desafíos activos en este momento.',
    'checkout.title': 'Pago Seguro',
    'checkout.secure': 'Tus datos están encriptados por Deal Voy',
    'checkout.payment_method': 'Método de Pago',
    'checkout.pay': 'Pagar',
    'checkout.success': '¡Pago Confirmado!',
    'checkout.redirect': 'Redirigiendo a tu cupón...',
    'ad.sponsored': 'Patrocinado',
    'notification.deal': 'Oferta',
    'notification.alert': 'Alerta',
    'notification.event': 'Evento',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.explore': 'Explorer',
    'nav.challenges': 'Défis',
    'nav.saved': 'Enregistré',
    'nav.upload': 'Télécharger',
    'nav.profile': 'Profil',
    'nav.travel': 'Itinéraires',
    'nav.vendor': 'Portail B2B',
    'nav.seasonal': 'Saisonnier',
    'nav.admin': 'Admin',
    'search.placeholder': "Où voulez-vous économiser aujourd'hui?",
    'hero.title': 'Deal Voy: Économies en mouvement',
    'hero.subtitle':
      'Découvrez des réductions exclusives et planifiez des itinéraires.',
    'coupon.reserve': 'Obtenir Coupon',
    'coupon.reserved': 'Coupon Sécurisé',
    'coupon.available': 'Disponible',
    'coupon.menu': 'Voir Menu',
    'coupon.reviews': 'Avis',
    'coupon.add_review': 'Ajouter un avis',
    'coupon.rating': 'Votre note',
    'coupon.comment': 'Votre commentaire',
    'coupon.submit_review': 'Envoyer',
    'coupon.loyalty': 'Programme de fidélité',
    'coupon.collect_stamp': 'Vous avez collecté des timbres',
    'coupon.reward': 'Récompense',
    'coupon.report': 'Signaler un problème',
    'coupon.verify': 'Cette offre est-elle toujours active?',
    'coupon.verified_at': 'Vérifié à',
    'upload.history': 'Historique',
    'upload.camera': 'Caméra',
    'upload.pending': 'En attente',
    'upload.verified': 'Vérifié',
    'upload.rejected': 'Rejeté',
    'mood.title': 'Quelle est votre humeur?',
    'common.refresh': 'Actualiser',
    'travel.title': 'Planificateur de voyage',
    'travel.subtitle': 'Planifiez vos économies, où que vous soyez.',
    'travel.gps': 'GPS Actuel',
    'travel.plan_destination': 'Planifier Destination',
    'travel.search_placeholder': 'Où allez-vous? (ex: Orlando, FL)',
    'travel.showing_offers_for': 'Affichage des offres pour:',
    'travel.events': 'Événements locaux',
    'travel.savings': 'Économies totales',
    'travel.my_itinerary': 'Mon Itinéraire',
    'travel.offers_found': 'offres trouvées',
    'travel.no_offers': 'Aucune offre trouvée dans cette région.',
    'travel.back_to_gps': 'Retour au GPS actuel',
    'travel.itinerary_title': "Mon Itinéraire d'Économies",
    'travel.saved_coupons': 'coupons enregistrés pour votre voyage.',
    'travel.empty_itinerary': 'Votre itinéraire est vide',
    'travel.empty_desc':
      'Explorez les offres et cliquez sur "Add Trip" pour organiser votre voyage.',
    'travel.explore_offers': 'Explorer les Offres',
    'seasonal.title': 'Calendrier saisonnier',
    'notifications.title': 'Notifications',
    'notifications.empty': 'Aucune notification',
    'notifications.mark_read': 'Marquer comme lu',
    'offline.mode': 'Mode hors ligne',
    'offline.message': 'Vous êtes hors ligne.',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'common.search': 'Chercher',
    'common.hide': 'Cacher',
    'common.show': 'Montrer',
    'common.share': 'Partager',
    'common.view_all': 'Voir tout',
    'common.load_more': 'Charger plus',
    'map.error': 'Impossible de charger la carte.',
    'map.loading': 'Chargement de la carte...',
    'home.detecting_location': "Détection de l'emplacement...",
    'home.current_location': 'Emplacement actuel:',
    'home.featured_deals': 'Offres en Vedette',
    'home.travel_card_title': 'Vous voyagez? Économisez en chemin.',
    'home.travel_card_desc':
      'Tracez votre itinéraire et découvrez des arrêts stratégiques avec des réductions exclusives.',
    'home.plan_route': "Planifier l'itinéraire",
    'home.tracked_deals': 'Trouvailles Web (Tracked)',
    'home.all_offers': 'Toutes les Offres',
    'home.offers_of': 'Offres de',
    'home.no_offers': 'Aucune offre trouvée pour cette catégorie.',
    'explore.filters': 'Filtres',
    'explore.filter_title': 'Filtrer les Offres',
    'explore.filter_desc': 'Trouvez ce dont vous avez besoin',
    'explore.max_distance': 'Distance Max',
    'explore.categories': 'Catégories',
    'explore.apply_filters': 'Appliquer Filtres',
    'explore.view_map': 'Voir Carte',
    'explore.view_list': 'Voir Liste',
    'vendor.dashboard': 'Tableau de bord partenaire',
    'vendor.add': 'Nouvelle Campagne',
    'challenges.title': 'Défis et récompenses',
    'challenges.subtitle':
      'Terminez des missions, gagnez des badges et débloquez des réductions exclusives.',
    'challenges.active': 'Actif',
    'challenges.available': 'Disponible',
    'challenges.completed': 'Terminé',
    'challenges.reward': 'Récompense',
    'challenges.progress': 'Progrès',
    'challenges.accept': 'Accepter le défi',
    'challenges.empty': "Vous n'avez aucun défi actif pour le moment.",
    'checkout.title': 'Paiement sécurisé',
    'checkout.secure': 'Vos données sont cryptées par Deal Voy',
    'checkout.payment_method': 'Moyen de paiement',
    'checkout.pay': 'Payer',
    'checkout.success': 'Paiement confirmé!',
    'checkout.redirect': 'Redirection vers votre coupon...',
    'ad.sponsored': 'Sponsorisé',
    'notification.deal': 'Accord',
    'notification.alert': 'Alerte',
    'notification.event': 'Événement',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.explore': 'Entdecken',
    'nav.challenges': 'Herausforderungen',
    'nav.saved': 'Gespeichert',
    'nav.upload': 'Hochladen',
    'nav.profile': 'Profil',
    'nav.travel': 'Reiserouten',
    'nav.vendor': 'B2B Portal',
    'nav.seasonal': 'Saisonal',
    'nav.admin': 'Admin',
    'search.placeholder': 'Wo möchten Sie heute sparen?',
    'hero.title': 'Deal Voy: Sparen in Bewegung',
    'hero.subtitle':
      'Entdecken Sie exklusive Rabatte und planen Sie intelligente Routen.',
    'coupon.reserve': 'Gutschein erhalten',
    'coupon.reserved': 'Gutschein gesichert',
    'coupon.available': 'Verfügbar',
    'coupon.menu': 'Menü ansehen',
    'coupon.reviews': 'Bewertungen',
    'coupon.add_review': 'Bewertung hinzufügen',
    'coupon.rating': 'Ihre Bewertung',
    'coupon.comment': 'Ihr Kommentar',
    'coupon.submit_review': 'Absenden',
    'coupon.loyalty': 'Treueprogramm',
    'coupon.collect_stamp': 'Sie haben Stempel gesammelt',
    'coupon.reward': 'Belohnung',
    'coupon.report': 'Problem melden',
    'coupon.verify': 'Ist dieses Angebot noch aktiv?',
    'coupon.verified_at': 'Überprüft am',
    'upload.history': 'Verlauf',
    'upload.camera': 'Kamera',
    'upload.pending': 'Ausstehend',
    'upload.verified': 'Verifiziert',
    'upload.rejected': 'Abgelehnt',
    'mood.title': 'Wie ist Ihre Stimmung?',
    'common.refresh': 'Aktualisieren',
    'travel.title': 'Reiseplaner',
    'travel.subtitle': 'Planen Sie Ihre Ersparnisse, egal wo Sie sind.',
    'travel.gps': 'Aktuelles GPS',
    'travel.plan_destination': 'Ziel planen',
    'travel.search_placeholder': 'Wohin gehen Sie? (z. B. Orlando, FL)',
    'travel.showing_offers_for': 'Angebote für:',
    'travel.events': 'Lokale Veranstaltungen',
    'travel.savings': 'Gesamtersparnis',
    'travel.my_itinerary': 'Meine Reiseroute',
    'travel.offers_found': 'Angebote gefunden',
    'travel.no_offers': 'Keine Angebote in dieser Region gefunden.',
    'travel.back_to_gps': 'Zurück zum aktuellen GPS',
    'travel.itinerary_title': 'Meine Spar-Reiseroute',
    'travel.saved_coupons': 'gespeicherte Coupons für Ihre Reise.',
    'travel.empty_itinerary': 'Ihre Reiseroute ist leer',
    'travel.empty_desc':
      'Entdecken Sie Angebote und klicken Sie auf "Add Trip", um Ihre Reise zu organisieren.',
    'travel.explore_offers': 'Angebote entdecken',
    'seasonal.title': 'Saisonkalender',
    'notifications.title': 'Benachrichtigungen',
    'notifications.empty': 'Keine neuen Benachrichtigungen',
    'notifications.mark_read': 'Als gelesen markieren',
    'offline.mode': 'Offline-Modus',
    'offline.message': 'Sie sind offline.',
    'common.view': 'Ansehen',
    'common.close': 'Schließen',
    'common.search': 'Suchen',
    'common.hide': 'Verbergen',
    'common.show': 'Anzeigen',
    'common.share': 'Teilen',
    'common.view_all': 'Alle ansehen',
    'common.load_more': 'Mehr laden',
    'map.error': 'Karte konnte nicht geladen werden.',
    'map.loading': 'Karte wird geladen...',
    'home.detecting_location': 'Standort wird ermittelt...',
    'home.current_location': 'Aktueller Standort:',
    'home.featured_deals': 'Vorgestellte Angebote',
    'home.travel_card_title': 'Reisen Sie? Sparen Sie unterwegs.',
    'home.travel_card_desc':
      'Planen Sie Ihre Route und entdecken Sie strategische Stopps mit exklusiven Rabatten.',
    'home.plan_route': 'Route jetzt planen',
    'home.tracked_deals': 'Web-Funde (Tracked)',
    'home.all_offers': 'Alle Angebote',
    'home.offers_of': 'Angebote von',
    'home.no_offers': 'Keine Angebote für diese Kategorie gefunden.',
    'explore.filters': 'Filter',
    'explore.filter_title': 'Angebote filtern',
    'explore.filter_desc': 'Finden Sie, was Sie brauchen',
    'explore.max_distance': 'Maximale Entfernung',
    'explore.categories': 'Kategorien',
    'explore.apply_filters': 'Filter anwenden',
    'explore.view_map': 'Karte ansehen',
    'explore.view_list': 'Liste ansehen',
    'vendor.dashboard': 'Partner-Dashboard',
    'vendor.add': 'Neue Kampagne',
    'challenges.title': 'Herausforderungen und Belohnungen',
    'challenges.subtitle':
      'Erfüllen Sie Missionen, verdienen Sie Abzeichen und schalten Sie exklusive Rabatte frei.',
    'challenges.active': 'Aktiv',
    'challenges.available': 'Verfügbar',
    'challenges.completed': 'Abgeschlossen',
    'challenges.reward': 'Belohnung',
    'challenges.progress': 'Fortschritt',
    'challenges.accept': 'Herausforderung annehmen',
    'challenges.empty': 'Sie haben derzeit keine aktiven Herausforderungen.',
    'checkout.title': 'Sichere Kasse',
    'checkout.secure': 'Ihre Daten werden von Deal Voy verschlüsselt',
    'checkout.payment_method': 'Zahlungsmethode',
    'checkout.pay': 'Zahlen',
    'checkout.success': 'Zahlung bestätigt!',
    'checkout.redirect': 'Weiterleitung zu Ihrem Gutschein...',
    'ad.sponsored': 'Gesponsert',
    'notification.deal': 'Deal',
    'notification.alert': 'Alarm',
    'notification.event': 'Ereignis',
  },
  it: {
    'nav.home': 'Home',
    'nav.explore': 'Esplora',
    'nav.challenges': 'Sfide',
    'nav.saved': 'Salvati',
    'nav.upload': 'Carica',
    'nav.profile': 'Profilo',
    'nav.travel': 'Itinerari',
    'nav.vendor': 'Portale B2B',
    'nav.seasonal': 'Stagionale',
    'nav.admin': 'Admin',
    'search.placeholder': 'Dove vuoi risparmiare oggi?',
    'hero.title': 'Deal Voy: Risparmio in movimento',
    'hero.subtitle':
      'Scopri sconti esclusivi e pianifica itinerari intelligenti.',
    'coupon.reserve': 'Ottieni Coupon',
    'coupon.reserved': 'Coupon Assicurato',
    'coupon.available': 'Disponibili',
    'coupon.menu': 'Vedi Menu',
    'coupon.reviews': 'Recensioni',
    'coupon.add_review': 'Aggiungi recensione',
    'coupon.rating': 'La tua valutazione',
    'coupon.comment': 'Il tuo commento',
    'coupon.submit_review': 'Invia',
    'coupon.loyalty': 'Programma Fedeltà',
    'coupon.collect_stamp': 'Hai raccolto timbri',
    'coupon.reward': 'Premio',
    'coupon.report': 'Segnala problema',
    'coupon.verify': 'Questa offerta è ancora attiva?',
    'coupon.verified_at': 'Verificato il',
    'upload.history': 'Cronologia',
    'upload.camera': 'Fotocamera',
    'upload.pending': 'In attesa',
    'upload.verified': 'Verificato',
    'upload.rejected': 'Rifiutato',
    'mood.title': 'Qual è il tuo umore?',
    'common.refresh': 'Aggiorna',
    'travel.title': 'Pianificatore di viaggio',
    'travel.subtitle': 'Pianifica i tuoi risparmi, ovunque tu sia.',
    'travel.gps': 'GPS Attuale',
    'travel.plan_destination': 'Pianifica Destinazione',
    'travel.search_placeholder': 'Dove stai andando? (es. Orlando, FL)',
    'travel.showing_offers_for': 'Mostrando offerte per:',
    'travel.events': 'Eventi locali',
    'travel.savings': 'Risparmio totale',
    'travel.my_itinerary': 'Il mio Itinerario',
    'travel.offers_found': 'offerte trovate',
    'travel.no_offers': 'Nessuna offerta trovata in questa regione.',
    'travel.back_to_gps': 'Torna al GPS attuale',
    'travel.itinerary_title': 'Il mio Itinerario di Risparmio',
    'travel.saved_coupons': 'coupon salvati per il tuo viaggio.',
    'travel.empty_itinerary': 'Il tuo itinerario è vuoto',
    'travel.empty_desc':
      'Esplora le offerte e clicca su "Add Trip" per organizzare il tuo viaggio.',
    'travel.explore_offers': 'Esplora Offerte',
    'seasonal.title': 'Calendario stagionale',
    'notifications.title': 'Notifiche',
    'notifications.empty': 'Nessuna nuova notifica',
    'notifications.mark_read': 'Segna come letto',
    'offline.mode': 'Modalità Offline',
    'offline.message': 'Sei offline.',
    'common.view': 'Vedi',
    'common.close': 'Chiudi',
    'common.search': 'Cerca',
    'common.hide': 'Nascondi',
    'common.show': 'Mostra',
    'common.share': 'Condividi',
    'common.view_all': 'Vedi tutto',
    'common.load_more': 'Carica altro',
    'map.error': 'Impossibile caricare la mappa.',
    'map.loading': 'Caricamento mappa...',
    'home.detecting_location': 'Rilevamento posizione...',
    'home.current_location': 'Posizione attuale:',
    'home.featured_deals': 'Offerte in Evidenza',
    'home.travel_card_title': 'In viaggio? Risparmia lungo la strada.',
    'home.travel_card_desc':
      'Traccia il tuo percorso e scopri soste strategiche con sconti esclusivi.',
    'home.plan_route': 'Pianifica Percorso',
    'home.tracked_deals': 'Scoperte Web (Tracked)',
    'home.all_offers': 'Tutte le Offerte',
    'home.offers_of': 'Offerte di',
    'home.no_offers': 'Nessuna offerta trovata per questa categoria.',
    'explore.filters': 'Filtri',
    'explore.filter_title': 'Filtra Offerte',
    'explore.filter_desc': 'Trova ciò di cui hai bisogno',
    'explore.max_distance': 'Distanza Massima',
    'explore.categories': 'Categorie',
    'explore.apply_filters': 'Applica Filtri',
    'explore.view_map': 'Vedi Mappa',
    'explore.view_list': 'Vedi Elenco',
    'vendor.dashboard': 'Dashboard Partner',
    'vendor.add': 'Nuova Campagna',
    'challenges.title': 'Sfide e premi',
    'challenges.subtitle':
      'Completa le missioni, guadagna badge e sblocca sconti esclusivi.',
    'challenges.active': 'Attivo',
    'challenges.available': 'Disponibile',
    'challenges.completed': 'Completato',
    'challenges.reward': 'Premio',
    'challenges.progress': 'Progresso',
    'challenges.accept': 'Accetta sfida',
    'challenges.empty': 'Non hai sfide attive al momento.',
    'checkout.title': 'Pagamento sicuro',
    'checkout.secure': 'I tuoi dati sono crittografati da Deal Voy',
    'checkout.payment_method': 'Metodo di pagamento',
    'checkout.pay': 'Paga',
    'checkout.success': 'Pagamento confermato!',
    'checkout.redirect': 'Reindirizzamento al tuo coupon...',
    'ad.sponsored': 'Sponsorizzato',
    'notification.deal': 'Affare',
    'notification.alert': 'Avviso',
    'notification.event': 'Evento',
  },
  zh: {
    'nav.home': '首页',
    'nav.explore': '探索',
    'nav.challenges': '挑战',
    'nav.saved': '已保存',
    'nav.upload': '上传',
    'nav.profile': '个人资料',
    'nav.travel': '行程',
    'nav.vendor': 'B2B门户',
    'nav.seasonal': '季节性',
    'nav.admin': 'Admin',
    'search.placeholder': '您今天想在哪里省钱？',
    'hero.title': 'Deal Voy: 移动中的储蓄',
    'hero.subtitle': '发现独家折扣并规划智能行程。',
    'coupon.reserve': '获取优惠券',
    'coupon.reserved': '优惠券已获得',
    'coupon.available': '可用',
    'coupon.menu': '查看菜单',
    'coupon.reviews': '评论',
    'coupon.add_review': '添加评论',
    'coupon.rating': '您的评分',
    'coupon.comment': '您的评论',
    'coupon.submit_review': '提交',
    'coupon.loyalty': '忠诚度计划',
    'coupon.collect_stamp': '您已收集印章',
    'coupon.reward': '奖励',
    'coupon.report': '报告问题',
    'coupon.verify': '此优惠仍然有效吗？',
    'coupon.verified_at': '验证于',
    'upload.history': '历史',
    'upload.camera': '相机',
    'upload.pending': '待定',
    'upload.verified': '已验证',
    'upload.rejected': '已拒绝',
    'mood.title': '您今天的心情如何？',
    'common.refresh': '刷新',
    'travel.title': '旅行计划',
    'travel.subtitle': '规划您的储蓄，无论您身在何处。',
    'travel.gps': '当前 GPS',
    'travel.plan_destination': '规划目的地',
    'travel.search_placeholder': '您要去哪里？ (例如: Orlando, FL)',
    'travel.showing_offers_for': '显示优惠:',
    'travel.events': '当地活动',
    'travel.savings': '总储蓄',
    'travel.my_itinerary': '我的行程',
    'travel.offers_found': '找到的优惠',
    'travel.no_offers': '该地区未找到优惠。',
    'travel.back_to_gps': '返回当前 GPS',
    'travel.itinerary_title': '我的储蓄行程',
    'travel.saved_coupons': '为您保存的优惠券。',
    'travel.empty_itinerary': '您的行程是空的',
    'travel.empty_desc': '探索优惠并点击“Add Trip”来组织您的旅程。',
    'travel.explore_offers': '探索优惠',
    'seasonal.title': '季节日历',
    'notifications.title': '通知',
    'notifications.empty': '没有新通知',
    'notifications.mark_read': '标记为已读',
    'offline.mode': '离线模式',
    'offline.message': '您处于离线状态。',
    'common.view': '查看',
    'common.close': '关闭',
    'common.search': '搜索',
    'common.hide': '隐藏',
    'common.show': '显示',
    'common.share': '分享',
    'common.view_all': '查看全部',
    'common.load_more': '加载更多',
    'map.error': '无法加载地图。',
    'map.loading': '正在加载地图...',
    'home.detecting_location': '正在检测位置...',
    'home.current_location': '当前位置:',
    'home.featured_deals': '精选优惠',
    'home.travel_card_title': '去旅行？ 一路省钱。',
    'home.travel_card_desc': '规划路线，发现加油站、餐厅和酒店的独家折扣。',
    'home.plan_route': '立即规划路线',
    'home.tracked_deals': '网络发现 (Tracked)',
    'home.all_offers': '所有优惠',
    'home.offers_of': '优惠类别',
    'home.no_offers': '暂时没有找到此类别的优惠。',
    'explore.filters': '筛选',
    'explore.filter_title': '筛选优惠',
    'explore.filter_desc': '找到您需要的',
    'explore.max_distance': '最大距离',
    'explore.categories': '类别',
    'explore.apply_filters': '应用筛选',
    'explore.view_map': '查看地图',
    'explore.view_list': '查看列表',
    'vendor.dashboard': '合作伙伴仪表板',
    'vendor.add': '新活动',
    'challenges.title': '挑战与奖励',
    'challenges.subtitle': '完成任务，赢取徽章并解锁独家折扣。',
    'challenges.active': '活跃',
    'challenges.available': '可用',
    'challenges.completed': '已完成',
    'challenges.reward': '奖励',
    'challenges.progress': '进度',
    'challenges.accept': '接受挑战',
    'challenges.empty': '您目前没有活跃的挑战。',
    'checkout.title': '安全结账',
    'checkout.secure': '您的数据由 Deal Voy 加密',
    'checkout.payment_method': '付款方式',
    'checkout.pay': '支付',
    'checkout.success': '付款已确认！',
    'checkout.redirect': '正在重定向到您的优惠券...',
    'ad.sponsored': '赞助',
    'notification.deal': '交易',
    'notification.alert': '警报',
    'notification.event': '事件',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.explore': '探索',
    'nav.challenges': 'チャレンジ',
    'nav.saved': '保存済み',
    'nav.upload': 'アップロード',
    'nav.profile': 'プロフィール',
    'nav.travel': '旅程',
    'nav.vendor': 'B2Bポータル',
    'nav.seasonal': '季節',
    'nav.admin': 'Admin',
    'search.placeholder': '今日どこで節約しますか？',
    'hero.title': 'Deal Voy: 移動中の節約',
    'hero.subtitle': '限定割引を見つけて、スマートな旅程を計画しましょう。',
    'coupon.reserve': 'クーポンを入手',
    'coupon.reserved': 'クーポン確保',
    'coupon.available': '利用可能',
    'coupon.menu': 'メニューを見る',
    'coupon.reviews': 'レビュー',
    'coupon.add_review': 'レビューを追加',
    'coupon.rating': 'あなたの評価',
    'coupon.comment': 'あなたのコメント',
    'coupon.submit_review': '送信',
    'coupon.loyalty': 'ロイヤルティプログラム',
    'coupon.collect_stamp': 'スタンプを集めました',
    'coupon.reward': '報酬',
    'coupon.report': '問題を報告',
    'coupon.verify': 'このオファーはまだ有効ですか？',
    'coupon.verified_at': '確認済み',
    'upload.history': '履歴',
    'upload.camera': 'カメラ',
    'upload.pending': '保留中',
    'upload.verified': '確認済み',
    'upload.rejected': '拒否',
    'mood.title': '今日の気分は？',
    'common.refresh': '更新',
    'travel.title': '旅行プランナー',
    'travel.subtitle': 'どこにいても、節約を計画しましょう。',
    'travel.gps': '現在のGPS',
    'travel.plan_destination': '目的地を計画',
    'travel.search_placeholder': 'どこへ行きますか？ (例: Orlando, FL)',
    'travel.showing_offers_for': '表示中のオファー:',
    'travel.events': 'ローカルイベント',
    'travel.savings': '総節約額',
    'travel.my_itinerary': '私の旅程',
    'travel.offers_found': '件のオファーが見つかりました',
    'travel.no_offers': 'この地域にはオファーがありません。',
    'travel.back_to_gps': '現在のGPSに戻る',
    'travel.itinerary_title': '私の節約旅程',
    'travel.saved_coupons': '旅行用に保存されたクーポン。',
    'travel.empty_itinerary': '旅程は空です',
    'travel.empty_desc':
      'オファーを探索し、「Add Trip」をクリックして旅行を整理してください。',
    'travel.explore_offers': 'オファーを探索',
    'seasonal.title': '季節カレンダー',
    'notifications.title': '通知',
    'notifications.empty': '新しい通知はありません',
    'notifications.mark_read': '既読にする',
    'offline.mode': 'オフラインモード',
    'offline.message': 'オフラインです。',
    'common.view': '表示',
    'common.close': '閉じる',
    'common.search': '検索',
    'common.hide': '隠す',
    'common.show': '表示',
    'common.share': '共有',
    'common.view_all': 'すべて表示',
    'common.load_more': 'さらに読み込む',
    'map.error': '地図を読み込めませんでした。',
    'map.loading': '地図を読み込んでいます...',
    'home.detecting_location': '位置情報を検出中...',
    'home.current_location': '現在の位置:',
    'home.featured_deals': '注目のオファー',
    'home.travel_card_title': '旅行ですか？ 道中で節約。',
    'home.travel_card_desc':
      'ルートを計画し、ガソリンスタンド、レストラン、ホテルでの限定割引を見つけましょう。',
    'home.plan_route': '今すぐルートを計画',
    'home.tracked_deals': 'Webの掘り出し物 (Tracked)',
    'home.all_offers': 'すべてのオファー',
    'home.offers_of': 'のオファー',
    'home.no_offers': '現在、このカテゴリのオファーは見つかりませんでした。',
    'explore.filters': 'フィルター',
    'explore.filter_title': 'オファーをフィルタリング',
    'explore.filter_desc': '必要なものを見つける',
    'explore.max_distance': '最大距離',
    'explore.categories': 'カテゴリ',
    'explore.apply_filters': 'フィルターを適用',
    'explore.view_map': '地図を表示',
    'explore.view_list': 'リストを表示',
    'vendor.dashboard': 'パートナーダッシュボード',
    'vendor.add': '新しいキャンペーン',
    'challenges.title': 'チャレンジと報酬',
    'challenges.subtitle':
      'ミッションを完了し、バッジを獲得して、限定割引のロックを解除します。',
    'challenges.active': 'アクティブ',
    'challenges.available': '利用可能',
    'challenges.completed': '完了',
    'challenges.reward': '報酬',
    'challenges.progress': '進捗',
    'challenges.accept': 'チャレンジを受け入れる',
    'challenges.empty': '現在アクティブなチャレンジはありません。',
    'checkout.title': '安全なチェックアウト',
    'checkout.secure': 'データは Deal Voy によって暗号化されています',
    'checkout.payment_method': '支払方法',
    'checkout.pay': '支払う',
    'checkout.success': '支払いが確認されました！',
    'checkout.redirect': 'クーポンにリダイレクトしています...',
    'ad.sponsored': 'スポンサー',
    'notification.deal': '取引',
    'notification.alert': 'アラート',
    'notification.event': 'イベント',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt')

  const t = (key: string) => {
    // Basic fallback to Portuguese if key missing in current language
    return translations[language][key] || translations['pt'][key] || key
  }

  return React.createElement(
    LanguageContext.Provider,
    { value: { language, setLanguage, t } },
    children,
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
