import React, { createContext, useContext, useState } from 'react'

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'nav.home': 'Início',
    'nav.explore': 'Explorar',
    'nav.challenges': 'Desafios',
    'nav.saved': 'Salvos',
    'nav.upload': 'Subir Doc',
    'nav.profile': 'Perfil',
    'nav.travel': 'Roteiros',
    'nav.vendor': 'Portal B2B',
    'nav.seasonal': 'Sazonal',
    'search.placeholder': 'Onde você quer economizar hoje?',
    'hero.title': 'Deal Voy: Economia em movimento',
    'hero.subtitle':
      'Descubra descontos exclusivos e planeje roteiros inteligentes na sua região.',
    'coupon.reserve': 'Pegar Cupom',
    'coupon.reserved': 'Cupom Garantido',
    'coupon.available': 'Disponíveis',
    'coupon.menu': 'Ver Menu Traduzido',
    'coupon.reviews': 'Avaliações',
    'coupon.add_review': 'Adicionar Avaliação',
    'coupon.rating': 'Sua nota',
    'coupon.comment': 'Seu comentário',
    'coupon.submit_review': 'Enviar Avaliação',
    'coupon.loyalty': 'Programa de Fidelidade',
    'coupon.collect_stamp': 'Você tem selos acumulados',
    'coupon.reward': 'Recompensa',
    'coupon.report': 'Reportar Problema',
    'coupon.verify': 'Esta oferta ainda está ativa?',
    'coupon.verified_at': 'Verificado em',
    'upload.history': 'Histórico',
    'upload.camera': 'Câmera',
    'upload.pending': 'Em Análise',
    'upload.verified': 'Verificado',
    'upload.rejected': 'Rejeitado',
    'mood.title': 'Qual sua vibe hoje?',
    'common.refresh': 'Atualizar Ofertas',
    'travel.title': 'Planejador de Viagem',
    'travel.events': 'Eventos Locais',
    'travel.savings': 'Economia Total',
    'seasonal.title': 'Calendário Sazonal',
    'notifications.title': 'Notificações',
    'notifications.empty': 'Sem novas notificações',
    'notifications.mark_read': 'Marcar como lida',
    'offline.mode': 'Modo Offline',
    'offline.message': 'Você está offline. Exibindo roteiros baixados.',
    'common.view': 'Ver',
    'common.close': 'Fechar',
    'vendor.dashboard': 'Painel do Parceiro',
    'vendor.add': 'Nova Campanha',
    'challenges.title': 'Desafios & Recompensas',
    'challenges.subtitle':
      'Complete missões, ganhe badges e desbloqueie descontos exclusivos.',
    'challenges.active': 'Ativos',
    'challenges.available': 'Disponíveis',
    'challenges.completed': 'Concluídos',
    'challenges.reward': 'Recompensa',
    'challenges.progress': 'Progresso',
    'challenges.accept': 'Aceitar Desafio',
    'challenges.empty': 'Você não tem desafios ativos no momento.',
    'checkout.title': 'Checkout Seguro',
    'checkout.secure': 'Seus dados estão criptografados por Deal Voy',
    'checkout.payment_method': 'Forma de Pagamento',
    'checkout.pay': 'Pagar',
    'checkout.success': 'Pagamento Confirmado!',
    'checkout.redirect': 'Redirecionando para seu cupom...',
    'ad.sponsored': 'Patrocinado',
    'notification.deal': 'Oferta',
    'notification.alert': 'Alerta',
    'notification.event': 'Evento',
  },
  en: {
    'nav.home': 'Home',
    'nav.explore': 'Explore',
    'nav.challenges': 'Challenges',
    'nav.saved': 'Saved',
    'nav.upload': 'Upload Doc',
    'nav.profile': 'Profile',
    'nav.travel': 'Itineraries',
    'nav.vendor': 'B2B Portal',
    'nav.seasonal': 'Seasonal',
    'search.placeholder': 'Where do you want to save today?',
    'hero.title': 'Deal Voy: Savings in Motion',
    'hero.subtitle':
      'Discover exclusive discounts and plan smart itineraries in your area.',
    'coupon.reserve': 'Get Coupon',
    'coupon.reserved': 'Coupon Secured',
    'coupon.available': 'Available',
    'coupon.menu': 'View Translated Menu',
    'coupon.reviews': 'Reviews',
    'coupon.add_review': 'Add Review',
    'coupon.rating': 'Your rating',
    'coupon.comment': 'Your comment',
    'coupon.submit_review': 'Submit Review',
    'coupon.loyalty': 'Loyalty Program',
    'coupon.collect_stamp': 'You have collected stamps',
    'coupon.reward': 'Reward',
    'coupon.report': 'Report Issue',
    'coupon.verify': 'Is this offer still active?',
    'coupon.verified_at': 'Verified at',
    'upload.history': 'History',
    'upload.camera': 'Camera',
    'upload.pending': 'Pending',
    'upload.verified': 'Verified',
    'upload.rejected': 'Rejected',
    'mood.title': 'What is your mood today?',
    'common.refresh': 'Refresh Deals',
    'travel.title': 'Trip Planner',
    'travel.events': 'Local Events',
    'travel.savings': 'Total Savings',
    'seasonal.title': 'Seasonal Calendar',
    'notifications.title': 'Notifications',
    'notifications.empty': 'No new notifications',
    'notifications.mark_read': 'Mark as read',
    'offline.mode': 'Offline Mode',
    'offline.message': 'You are offline. Showing downloaded itineraries.',
    'common.view': 'View',
    'common.close': 'Close',
    'vendor.dashboard': 'Partner Dashboard',
    'vendor.add': 'New Campaign',
    'challenges.title': 'Challenges & Rewards',
    'challenges.subtitle':
      'Complete missions, earn badges and unlock exclusive discounts.',
    'challenges.active': 'Active',
    'challenges.available': 'Available',
    'challenges.completed': 'Completed',
    'challenges.reward': 'Reward',
    'challenges.progress': 'Progress',
    'challenges.accept': 'Accept Challenge',
    'challenges.empty': 'You have no active challenges at the moment.',
    'checkout.title': 'Secure Checkout',
    'checkout.secure': 'Your data is encrypted by Deal Voy',
    'checkout.payment_method': 'Payment Method',
    'checkout.pay': 'Pay',
    'checkout.success': 'Payment Confirmed!',
    'checkout.redirect': 'Redirecting to your coupon...',
    'ad.sponsored': 'Sponsored',
    'notification.deal': 'Deal',
    'notification.alert': 'Alert',
    'notification.event': 'Event',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.explore': 'Explorar',
    'nav.challenges': 'Desafíos',
    'nav.saved': 'Guardados',
    'nav.upload': 'Subir Doc',
    'nav.profile': 'Perfil',
    'nav.travel': 'Rutas',
    'nav.vendor': 'Portal B2B',
    'nav.seasonal': 'Estacional',
    'search.placeholder': '¿Dónde quieres ahorrar hoy?',
    'hero.title': 'Deal Voy: Ahorro en Movimiento',
    'hero.subtitle':
      'Descubre descuentos exclusivos y planifica itinerarios inteligentes en tu zona.',
    'coupon.reserve': 'Obtener Cupón',
    'coupon.reserved': 'Cupón Asegurado',
    'coupon.available': 'Disponibles',
    'coupon.menu': 'Ver Menú Traducido',
    'coupon.reviews': 'Reseñas',
    'coupon.add_review': 'Agregar Reseña',
    'coupon.rating': 'Tu calificación',
    'coupon.comment': 'Tu comentario',
    'coupon.submit_review': 'Enviar Reseña',
    'coupon.loyalty': 'Programa de Lealtad',
    'coupon.collect_stamp': 'Tienes sellos acumulados',
    'coupon.reward': 'Recompensa',
    'coupon.report': 'Reportar Problema',
    'coupon.verify': '¿Sigue activa esta oferta?',
    'coupon.verified_at': 'Verificado en',
    'upload.history': 'Historial',
    'upload.camera': 'Cámara',
    'upload.pending': 'Pendiente',
    'upload.verified': 'Verificado',
    'upload.rejected': 'Rechazado',
    'mood.title': '¿Cuál es tu humor hoy?',
    'common.refresh': 'Actualizar Ofertas',
    'travel.title': 'Planificador de Viaje',
    'travel.events': 'Eventos Locales',
    'travel.savings': 'Ahorro Total',
    'seasonal.title': 'Calendario Estacional',
    'notifications.title': 'Notificaciones',
    'notifications.empty': 'Sin nuevas notificaciones',
    'notifications.mark_read': 'Marcar como leída',
    'offline.mode': 'Modo Offline',
    'offline.message': 'Estás sin internet. Mostrando itinerarios descargados.',
    'common.view': 'Ver',
    'common.close': 'Cerrar',
    'vendor.dashboard': 'Panel de Socio',
    'vendor.add': 'Nueva Campaña',
    'challenges.title': 'Desafíos y Recompensas',
    'challenges.subtitle':
      'Completa misiones, gana insignias y desbloquea descuentos exclusivos.',
    'challenges.active': 'Activos',
    'challenges.available': 'Disponibles',
    'challenges.completed': 'Completados',
    'challenges.reward': 'Recompensa',
    'challenges.progress': 'Progreso',
    'challenges.accept': 'Aceptar Desafío',
    'challenges.empty': 'No tienes desafíos activos en este momento.',
    'checkout.title': 'Pago Seguro',
    'checkout.secure': 'Tus datos están encriptados por Deal Voy',
    'checkout.payment_method': 'Método de Pago',
    'checkout.pay': 'Pagar',
    'checkout.success': '¡Pago Confirmado!',
    'checkout.redirect': 'Redirigiendo a tu cupón...',
    'ad.sponsored': 'Patrocinado',
    'notification.deal': 'Oferta',
    'notification.alert': 'Alerta',
    'notification.event': 'Evento',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.explore': 'Explorer',
    'nav.challenges': 'Défis',
    'nav.saved': 'Enregistré',
    'nav.upload': 'Télécharger',
    'nav.profile': 'Profil',
    'nav.travel': 'Itinéraires',
    'nav.vendor': 'Portail B2B',
    'nav.seasonal': 'Saisonnier',
    'search.placeholder': "Où voulez-vous économiser aujourd'hui?",
    'hero.title': 'Deal Voy: Économies en mouvement',
    'hero.subtitle':
      'Découvrez des réductions exclusives et planifiez des itinéraires.',
    'coupon.reserve': 'Obtenir Coupon',
    'coupon.reserved': 'Coupon Sécurisé',
    'coupon.available': 'Disponible',
    'coupon.menu': 'Voir Menu',
    'coupon.reviews': 'Avis',
    'coupon.add_review': 'Ajouter un avis',
    'coupon.rating': 'Votre note',
    'coupon.comment': 'Votre commentaire',
    'coupon.submit_review': 'Envoyer',
    'coupon.loyalty': 'Programme de fidélité',
    'coupon.collect_stamp': 'Vous avez collecté des timbres',
    'coupon.reward': 'Récompense',
    'coupon.report': 'Signaler un problème',
    'coupon.verify': 'Cette offre est-elle toujours active?',
    'coupon.verified_at': 'Vérifié à',
    'upload.history': 'Historique',
    'upload.camera': 'Caméra',
    'upload.pending': 'En attente',
    'upload.verified': 'Vérifié',
    'upload.rejected': 'Rejeté',
    'mood.title': 'Quelle est votre humeur?',
    'common.refresh': 'Actualiser',
    'travel.title': 'Planificateur de voyage',
    'travel.events': 'Événements locaux',
    'travel.savings': 'Économies totales',
    'seasonal.title': 'Calendrier saisonnier',
    'notifications.title': 'Notifications',
    'notifications.empty': 'Aucune notification',
    'notifications.mark_read': 'Marquer comme lu',
    'offline.mode': 'Mode hors ligne',
    'offline.message': 'Vous êtes hors ligne.',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'vendor.dashboard': 'Tableau de bord partenaire',
    'vendor.add': 'Nouvelle Campagne',
    'challenges.title': 'Défis et récompenses',
    'challenges.subtitle':
      'Terminez des missions, gagnez des badges et débloquez des réductions exclusives.',
    'challenges.active': 'Actif',
    'challenges.available': 'Disponible',
    'challenges.completed': 'Terminé',
    'challenges.reward': 'Récompense',
    'challenges.progress': 'Progrès',
    'challenges.accept': 'Accepter le défi',
    'challenges.empty': "Vous n'avez aucun défi actif pour le moment.",
    'checkout.title': 'Paiement sécurisé',
    'checkout.secure': 'Vos données sont cryptées par Deal Voy',
    'checkout.payment_method': 'Moyen de paiement',
    'checkout.pay': 'Payer',
    'checkout.success': 'Paiement confirmé!',
    'checkout.redirect': 'Redirection vers votre coupon...',
    'ad.sponsored': 'Sponsorisé',
    'notification.deal': 'Accord',
    'notification.alert': 'Alerte',
    'notification.event': 'Événement',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.explore': 'Entdecken',
    'nav.challenges': 'Herausforderungen',
    'nav.saved': 'Gespeichert',
    'nav.upload': 'Hochladen',
    'nav.profile': 'Profil',
    'nav.travel': 'Reiserouten',
    'nav.vendor': 'B2B Portal',
    'nav.seasonal': 'Saisonal',
    'search.placeholder': 'Wo möchten Sie heute sparen?',
    'hero.title': 'Deal Voy: Sparen in Bewegung',
    'hero.subtitle':
      'Entdecken Sie exklusive Rabatte und planen Sie intelligente Routen.',
    'coupon.reserve': 'Gutschein erhalten',
    'coupon.reserved': 'Gutschein gesichert',
    'coupon.available': 'Verfügbar',
    'coupon.menu': 'Menü ansehen',
    'coupon.reviews': 'Bewertungen',
    'coupon.add_review': 'Bewertung hinzufügen',
    'coupon.rating': 'Ihre Bewertung',
    'coupon.comment': 'Ihr Kommentar',
    'coupon.submit_review': 'Absenden',
    'coupon.loyalty': 'Treueprogramm',
    'coupon.collect_stamp': 'Sie haben Stempel gesammelt',
    'coupon.reward': 'Belohnung',
    'coupon.report': 'Problem melden',
    'coupon.verify': 'Ist dieses Angebot noch aktiv?',
    'coupon.verified_at': 'Überprüft am',
    'upload.history': 'Verlauf',
    'upload.camera': 'Kamera',
    'upload.pending': 'Ausstehend',
    'upload.verified': 'Verifiziert',
    'upload.rejected': 'Abgelehnt',
    'mood.title': 'Wie ist Ihre Stimmung?',
    'common.refresh': 'Aktualisieren',
    'travel.title': 'Reiseplaner',
    'travel.events': 'Lokale Veranstaltungen',
    'travel.savings': 'Gesamtersparnis',
    'seasonal.title': 'Saisonkalender',
    'notifications.title': 'Benachrichtigungen',
    'notifications.empty': 'Keine neuen Benachrichtigungen',
    'notifications.mark_read': 'Als gelesen markieren',
    'offline.mode': 'Offline-Modus',
    'offline.message': 'Sie sind offline.',
    'common.view': 'Ansehen',
    'common.close': 'Schließen',
    'vendor.dashboard': 'Partner-Dashboard',
    'vendor.add': 'Neue Kampagne',
    'challenges.title': 'Herausforderungen und Belohnungen',
    'challenges.subtitle':
      'Erfüllen Sie Missionen, verdienen Sie Abzeichen und schalten Sie exklusive Rabatte frei.',
    'challenges.active': 'Aktiv',
    'challenges.available': 'Verfügbar',
    'challenges.completed': 'Abgeschlossen',
    'challenges.reward': 'Belohnung',
    'challenges.progress': 'Fortschritt',
    'challenges.accept': 'Herausforderung annehmen',
    'challenges.empty': 'Sie haben derzeit keine aktiven Herausforderungen.',
    'checkout.title': 'Sichere Kasse',
    'checkout.secure': 'Ihre Daten werden von Deal Voy verschlüsselt',
    'checkout.payment_method': 'Zahlungsmethode',
    'checkout.pay': 'Zahlen',
    'checkout.success': 'Zahlung bestätigt!',
    'checkout.redirect': 'Weiterleitung zu Ihrem Gutschein...',
    'ad.sponsored': 'Gesponsert',
    'notification.deal': 'Deal',
    'notification.alert': 'Alarm',
    'notification.event': 'Ereignis',
  },
  it: {
    'nav.home': 'Home',
    'nav.explore': 'Esplora',
    'nav.challenges': 'Sfide',
    'nav.saved': 'Salvati',
    'nav.upload': 'Carica',
    'nav.profile': 'Profilo',
    'nav.travel': 'Itinerari',
    'nav.vendor': 'Portale B2B',
    'nav.seasonal': 'Stagionale',
    'search.placeholder': 'Dove vuoi risparmiare oggi?',
    'hero.title': 'Deal Voy: Risparmio in movimento',
    'hero.subtitle':
      'Scopri sconti esclusivi e pianifica itinerari intelligenti.',
    'coupon.reserve': 'Ottieni Coupon',
    'coupon.reserved': 'Coupon Assicurato',
    'coupon.available': 'Disponibili',
    'coupon.menu': 'Vedi Menu',
    'coupon.reviews': 'Recensioni',
    'coupon.add_review': 'Aggiungi recensione',
    'coupon.rating': 'La tua valutazione',
    'coupon.comment': 'Il tuo commento',
    'coupon.submit_review': 'Invia',
    'coupon.loyalty': 'Programma Fedeltà',
    'coupon.collect_stamp': 'Hai raccolto timbri',
    'coupon.reward': 'Premio',
    'coupon.report': 'Segnala problema',
    'coupon.verify': 'Questa offerta è ancora attiva?',
    'coupon.verified_at': 'Verificato il',
    'upload.history': 'Cronologia',
    'upload.camera': 'Fotocamera',
    'upload.pending': 'In attesa',
    'upload.verified': 'Verificato',
    'upload.rejected': 'Rifiutato',
    'mood.title': 'Qual è il tuo umore?',
    'common.refresh': 'Aggiorna',
    'travel.title': 'Pianificatore di viaggio',
    'travel.events': 'Eventi locali',
    'travel.savings': 'Risparmio totale',
    'seasonal.title': 'Calendario stagionale',
    'notifications.title': 'Notifiche',
    'notifications.empty': 'Nessuna nuova notifica',
    'notifications.mark_read': 'Segna come letto',
    'offline.mode': 'Modalità Offline',
    'offline.message': 'Sei offline.',
    'common.view': 'Vedi',
    'common.close': 'Chiudi',
    'vendor.dashboard': 'Dashboard Partner',
    'vendor.add': 'Nuova Campagna',
    'challenges.title': 'Sfide e premi',
    'challenges.subtitle':
      'Completa le missioni, guadagna badge e sblocca sconti esclusivi.',
    'challenges.active': 'Attivo',
    'challenges.available': 'Disponibile',
    'challenges.completed': 'Completato',
    'challenges.reward': 'Premio',
    'challenges.progress': 'Progresso',
    'challenges.accept': 'Accetta sfida',
    'challenges.empty': 'Non hai sfide attive al momento.',
    'checkout.title': 'Pagamento sicuro',
    'checkout.secure': 'I tuoi dati sono crittografati da Deal Voy',
    'checkout.payment_method': 'Metodo di pagamento',
    'checkout.pay': 'Paga',
    'checkout.success': 'Pagamento confermato!',
    'checkout.redirect': 'Reindirizzamento al tuo coupon...',
    'ad.sponsored': 'Sponsorizzato',
    'notification.deal': 'Affare',
    'notification.alert': 'Avviso',
    'notification.event': 'Evento',
  },
  zh: {
    'nav.home': '首页',
    'nav.explore': '探索',
    'nav.challenges': '挑战',
    'nav.saved': '已保存',
    'nav.upload': '上传',
    'nav.profile': '个人资料',
    'nav.travel': '行程',
    'nav.vendor': 'B2B门户',
    'nav.seasonal': '季节性',
    'search.placeholder': '您今天想在哪里省钱？',
    'hero.title': 'Deal Voy: 移动中的储蓄',
    'hero.subtitle': '发现独家折扣并规划智能行程。',
    'coupon.reserve': '获取优惠券',
    'coupon.reserved': '优惠券已获得',
    'coupon.available': '可用',
    'coupon.menu': '查看菜单',
    'coupon.reviews': '评论',
    'coupon.add_review': '添加评论',
    'coupon.rating': '您的评分',
    'coupon.comment': '您的评论',
    'coupon.submit_review': '提交',
    'coupon.loyalty': '忠诚度计划',
    'coupon.collect_stamp': '您已收集印章',
    'coupon.reward': '奖励',
    'coupon.report': '报告问题',
    'coupon.verify': '此优惠仍然有效吗？',
    'coupon.verified_at': '验证于',
    'upload.history': '历史',
    'upload.camera': '相机',
    'upload.pending': '待定',
    'upload.verified': '已验证',
    'upload.rejected': '已拒绝',
    'mood.title': '您今天的心情如何？',
    'common.refresh': '刷新',
    'travel.title': '旅行计划',
    'travel.events': '当地活动',
    'travel.savings': '总储蓄',
    'seasonal.title': '季节日历',
    'notifications.title': '通知',
    'notifications.empty': '没有新通知',
    'notifications.mark_read': '标记为已读',
    'offline.mode': '离线模式',
    'offline.message': '您处于离线状态。',
    'common.view': '查看',
    'common.close': '关闭',
    'vendor.dashboard': '合作伙伴仪表板',
    'vendor.add': '新活动',
    'challenges.title': '挑战与奖励',
    'challenges.subtitle': '完成任务，赢取徽章并解锁独家折扣。',
    'challenges.active': '活跃',
    'challenges.available': '可用',
    'challenges.completed': '已完成',
    'challenges.reward': '奖励',
    'challenges.progress': '进度',
    'challenges.accept': '接受挑战',
    'challenges.empty': '您目前没有活跃的挑战。',
    'checkout.title': '安全结账',
    'checkout.secure': '您的数据由 Deal Voy 加密',
    'checkout.payment_method': '付款方式',
    'checkout.pay': '支付',
    'checkout.success': '付款已确认！',
    'checkout.redirect': '正在重定向到您的优惠券...',
    'ad.sponsored': '赞助',
    'notification.deal': '交易',
    'notification.alert': '警报',
    'notification.event': '事件',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.explore': '探索',
    'nav.challenges': 'チャレンジ',
    'nav.saved': '保存済み',
    'nav.upload': 'アップロード',
    'nav.profile': 'プロフィール',
    'nav.travel': '旅程',
    'nav.vendor': 'B2Bポータル',
    'nav.seasonal': '季節',
    'search.placeholder': '今日どこで節約しますか？',
    'hero.title': 'Deal Voy: 移動中の節約',
    'hero.subtitle': '限定割引を見つけて、スマートな旅程を計画しましょう。',
    'coupon.reserve': 'クーポンを入手',
    'coupon.reserved': 'クーポン確保',
    'coupon.available': '利用可能',
    'coupon.menu': 'メニューを見る',
    'coupon.reviews': 'レビュー',
    'coupon.add_review': 'レビューを追加',
    'coupon.rating': 'あなたの評価',
    'coupon.comment': 'あなたのコメント',
    'coupon.submit_review': '送信',
    'coupon.loyalty': 'ロイヤルティプログラム',
    'coupon.collect_stamp': 'スタンプを集めました',
    'coupon.reward': '報酬',
    'coupon.report': '問題を報告',
    'coupon.verify': 'このオファーはまだ有効ですか？',
    'coupon.verified_at': '確認済み',
    'upload.history': '履歴',
    'upload.camera': 'カメラ',
    'upload.pending': '保留中',
    'upload.verified': '確認済み',
    'upload.rejected': '拒否',
    'mood.title': '今日の気分は？',
    'common.refresh': '更新',
    'travel.title': '旅行プランナー',
    'travel.events': 'ローカルイベント',
    'travel.savings': '総節約額',
    'seasonal.title': '季節カレンダー',
    'notifications.title': '通知',
    'notifications.empty': '新しい通知はありません',
    'notifications.mark_read': '既読にする',
    'offline.mode': 'オフラインモード',
    'offline.message': 'オフラインです。',
    'common.view': '表示',
    'common.close': '閉じる',
    'vendor.dashboard': 'パートナーダッシュボード',
    'vendor.add': '新しいキャンペーン',
    'challenges.title': 'チャレンジと報酬',
    'challenges.subtitle':
      'ミッションを完了し、バッジを獲得して、限定割引のロックを解除します。',
    'challenges.active': 'アクティブ',
    'challenges.available': '利用可能',
    'challenges.completed': '完了',
    'challenges.reward': '報酬',
    'challenges.progress': '進捗',
    'challenges.accept': 'チャレンジを受け入れる',
    'challenges.empty': '現在アクティブなチャレンジはありません。',
    'checkout.title': '安全なチェックアウト',
    'checkout.secure': 'データは Deal Voy によって暗号化されています',
    'checkout.payment_method': '支払方法',
    'checkout.pay': '支払う',
    'checkout.success': '支払いが確認されました！',
    'checkout.redirect': 'クーポンにリダイレクトしています...',
    'ad.sponsored': 'スポンサー',
    'notification.deal': '取引',
    'notification.alert': 'アラート',
    'notification.event': 'イベント',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt')

  const t = (key: string) => {
    // Basic fallback to Portuguese if key missing in current language
    return translations[language][key] || translations['pt'][key] || key
  }

  return React.createElement(
    LanguageContext.Provider,
    { value: { language, setLanguage, t } },
    children,
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
